devtools::install_github("ShixiangWang/VSHunter", build_vignettes = TRUE)
library(VSHunter)
vignette('VSHunter')
load(system.file("extdata/example_cn_list.RData", package = "VSHunter"))
tcga_frac = cnv_getLengthFraction(tcga_segTabs)
tcga_features = cnv_derivefeatures(CN_data = tcga_segTabs, cores = 1, genome_build = "hg19")
tcga_components = cnv_fitMixModels(CN_features = tcga_features, cores = 4)
tcga_sample_component_matrix = cnv_generateSbCMatrix(tcga_features, tcga_components, cores = 4)
tcga_sig_choose = cnv_chooseSigNumber(tcga_sample_component_matrix, nrun = 10, cores = 4)
tcga_sig_choose2 = cnv_chooseSigNumber(tcga_sample_component_matrix, nrun = 10, cores = 4, testRandom = FALSE)
tcga_signatures = cnv_extractSignatures(tcga_sample_component_matrix, nsig = 3, cores = 4)
w = NMF::basis(tcga_signatures)
tcga_exposure = cnv_quantifySigExposure(sample_by_component = tcga_sample_component_matrix, component_by_signature = w)
tcga_results = cnv_autoCaptureSignatures(tcga_sample_component_matrix, nrun=10, cores = 4)
cnv_plotDistributionProfile(tcga_frac)
cnv_plotDistributionProfile(tcga_frac, mode = "cd")
cnv_plotDistributionProfile(tcga_frac, mode = "cd" , fill = TRUE)

cnv_plotDistributionProfile()
cnv_plotFeatureDistribution()
cnv_plotMixComponents()
cnv_plotSignatures()